# Updated for 0.33.0: Lid Locked (https://github.com/realm/SwiftLint/releases)

# https://github.com/realm/SwiftLint/blob/master/Rules.md

disabled_rules:
- conditional_returns_on_newline # this breaks simple code
- discouraged_object_literal # use object_literal instead of this
- explicit_type_interface # this kills simple code
- fallthrough # added new default rule no_fallthrough_only (https://github.com/realm/SwiftLint/pull/2194) instead of this
- file_header # no need for my project
- missing_docs # Amekuru is developed privately
- no_extension_access_modifier # use extension_access_modifier instead of this
- no_grouping_extension # this kills readable code
- trailing_closure # to avoid a error when using .subscribe(onNext:) method

opt_in_rules:
# update those below list of rules with following command.
# swiftlint rules | awk -F "|" '$3 ~ "yes" { print $2 }' | tr -d ' ' | sed 's/^/  - /' | pbcopy
- anyobject_protocol
- array_init
- attributes
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- contains_over_first_not_nil
- convenience_type
- discouraged_object_literal
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_count
- empty_string
- empty_xctest_method
- explicit_acl
- explicit_enum_raw_value
- explicit_init
- explicit_self
- explicit_top_level_acl
- explicit_type_interface
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_header
- file_name
- file_types_order
- first_where
- force_unwrapping
- function_default_parameter_at_end
- identical_operands
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- last_where
- legacy_multiple
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- missing_docs
- modifier_order
- multiline_arguments
- multiline_arguments_brackets
- multiline_function_chains
- multiline_literal_brackets
- multiline_parameters
- multiline_parameters_brackets
- nimble_operator
- no_extension_access_modifier
- no_grouping_extension
- nslocalizedstring_key
- nslocalizedstring_require_bundle
- number_separator
- object_literal
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefixed_toplevel_constant
- private_action
- private_outlet
- prohibited_interface_builder
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- reduce_into
- redundant_nil_coalescing
- redundant_type_annotation
- required_deinit
- required_enum_case
- single_test_class
- sorted_first_last
- sorted_imports
- static_operator
- strict_fileprivate
- strong_iboutlet
- switch_case_on_newline
- toggle_bool
- trailing_closure
- type_contents_order
- unavailable_function
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- untyped_error_in_catch
- unused_declaration
- unused_import
- vertical_parameter_alignment_on_call
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- xct_specific_matcher
- yoda_condition

included:
- SwiftyVersionTracker

excluded:
- ExampleApp

line_length:
- 200   # warning
- 300   # error

type_body_length:
- 400   # warning
- 600   # error

file_length:
- 500   # warning
- 1000  # error

function_body_length:
- 100   # warning
- 200   # error

function_parameter_count:
- 6     # warning
- 10    # error
